In [1]:
import pandas as pd

df = pd.read_csv("short_selling.csv", encoding="utf-8")

In [2]:
df['report_date'] = pd.to_datetime(df['report_date'])

In [3]:
df_005930 = df[df['stock_code'] == '005930']
df_005930.sort_values('report_date', ascending=False).head(20)

,stock_code,company_name,report_date,market_code,security_type,short_volume_total,short_volume_uptick_applied,short_volume_uptick_exempt,total_volume,short_volume_ratio,short_amount_total,short_amount_uptick_applied,short_amount_uptick_exempt,total_amount,short_amount_ratio,source,source_screen_id
697802,005930,삼성전자,2026-03-20,KOSPI,주권,871381,341716,529665,42499576,2.05,174297078650,68424120950,105872957700,8466730499716,2.06,KRX,MDCSTAT301
694924,005930,삼성전자,2026-03-19,KOSPI,주권,1574488,809824,764664,29559268,5.33,316893032300,163109939200,153783093100,5955195854665,5.32,KRX,MDCSTAT301
692046,005930,삼성전자,2026-03-18,KOSPI,주권,888510,550958,337552,40259351,2.21,182794142200,112907987000,69886155200,8245401358813,2.22,KRX,MDCSTAT301
689167,005930,삼성전자,2026-03-17,KOSPI,주권,988960,639044,349916,29135546,3.39,193878982000,125150821750,68728160250,5711368340590,3.39,KRX,MDCSTAT301
686287,005930,삼성전자,2026-03-16,KOSPI,주권,777463,135634,641829,28269529,2.75,145622414450,25300601050,120321813400,5273027753250,2.76,KRX,MDCSTAT301
683406,005930,삼성전자,2026-03-13,KOSPI,주권,1547052,515520,1031532,26386624,5.86,283202360750,94358766550,188843594200,4835575044700,5.86,KRX,MDCSTAT301
680525,005930,삼성전자,2026-03-12,KOSPI,주권,853869,369684,484185,27460612,3.11,160084600200,69326395100,90758205100,5148439419250,3.11,KRX,MDCSTAT301
677644,005930,삼성전자,2026-03-11,KOSPI,주권,1003940,433319,570621,35631095,2.82,192629515200,83279507250,109350007950,6841140659906,2.82,KRX,MDCSTAT301
674763,005930,삼성전자,2026-03-10,KOSPI,주권,1659575,1150521,509054,50467350,3.29,311577899900,216381486500,95196413400,9489314157978,3.28,KRX,MDCSTAT301
671882,005930,삼성전자,2026-03-09,KOSPI,주권,2233430,552153,1681277,63586150,3.51,382202238450,94837128600,287365109850,10886125704700,3.51,KRX,MDCSTAT301
669002,005930,삼성전자,2026-03-06,KOSPI,주권,640227,477473,162754,42321957,1.51,119711891200,89284961150,30426930050,7877042133845,1.52,KRX,MDCSTAT301
666123,005930,삼성전자,2026-03-05,KOSPI,주권,1922650,1572150,350500,81292045,2.37,371399799900,303500056550,67899743350,15767405176166,2.36,KRX,MDCSTAT301
663244,005930,삼성전자,2026-03-04,KOSPI,주권,2564586,1994279,570307,138007637,1.86,468793205500,365654634550,103138570950,25074792242194,1.87,KRX,MDCSTAT301
660364,005930,삼성전자,2026-03-03,KOSPI,주권,1138390,1072592,65798,86333879,1.32,235742790600,222348189450,13394601150,17568799689650,1.34,KRX,MDCSTAT301
657484,005930,삼성전자,2026-02-27,KOSPI,주권,588952,568587,20365,68439905,0.86,128087874795,123692667295,4395207500,14807209714735,0.87,KRX,MDCSTAT301
654604,005930,삼성전자,2026-02-26,KOSPI,주권,1443985,1335850,108135,44281662,3.26,310141776500,287346159750,22795616750,9490901417838,3.27,KRX,MDCSTAT301
651724,005930,삼성전자,2026-02-25,KOSPI,주권,524788,366507,158281,36025232,1.46,106655543000,74527276250,32128266750,7313761303566,1.46,KRX,MDCSTAT301
648844,005930,삼성전자,2026-02-24,KOSPI,주권,205703,177786,27917,38821085,0.53,40668800050,35154749050,5514051000,7660700964858,0.53,KRX,MDCSTAT301
645963,005930,삼성전자,2026-02-23,KOSPI,주권,758644,512558,246086,35207920,2.15,147293823950,99320874150,47972949800,6822293771632,2.16,KRX,MDCSTAT301
643081,005930,삼성전자,2026-02-20,KOSPI,주권,234666,160027,74639,32355856,0.73,44511499650,30340859750,14170639900,6134580576330,0.73,KRX,MDCSTAT301

In [4]:
df_005930.sort_values('report_date', ascending=False).head(10)

,stock_code,company_name,report_date,market_code,security_type,short_volume_total,short_volume_uptick_applied,short_volume_uptick_exempt,total_volume,short_volume_ratio,short_amount_total,short_amount_uptick_applied,short_amount_uptick_exempt,total_amount,short_amount_ratio,source,source_screen_id
697802,005930,삼성전자,2026-03-20,KOSPI,주권,871381,341716,529665,42499576,2.05,174297078650,68424120950,105872957700,8466730499716,2.06,KRX,MDCSTAT301
694924,005930,삼성전자,2026-03-19,KOSPI,주권,1574488,809824,764664,29559268,5.33,316893032300,163109939200,153783093100,5955195854665,5.32,KRX,MDCSTAT301
692046,005930,삼성전자,2026-03-18,KOSPI,주권,888510,550958,337552,40259351,2.21,182794142200,112907987000,69886155200,8245401358813,2.22,KRX,MDCSTAT301
689167,005930,삼성전자,2026-03-17,KOSPI,주권,988960,639044,349916,29135546,3.39,193878982000,125150821750,68728160250,5711368340590,3.39,KRX,MDCSTAT301
686287,005930,삼성전자,2026-03-16,KOSPI,주권,777463,135634,641829,28269529,2.75,145622414450,25300601050,120321813400,5273027753250,2.76,KRX,MDCSTAT301
683406,005930,삼성전자,2026-03-13,KOSPI,주권,1547052,515520,1031532,26386624,5.86,283202360750,94358766550,188843594200,4835575044700,5.86,KRX,MDCSTAT301
680525,005930,삼성전자,2026-03-12,KOSPI,주권,853869,369684,484185,27460612,3.11,160084600200,69326395100,90758205100,5148439419250,3.11,KRX,MDCSTAT301
677644,005930,삼성전자,2026-03-11,KOSPI,주권,1003940,433319,570621,35631095,2.82,192629515200,83279507250,109350007950,6841140659906,2.82,KRX,MDCSTAT301
674763,005930,삼성전자,2026-03-10,KOSPI,주권,1659575,1150521,509054,50467350,3.29,311577899900,216381486500,95196413400,9489314157978,3.28,KRX,MDCSTAT301
671882,005930,삼성전자,2026-03-09,KOSPI,주권,2233430,552153,1681277,63586150,3.51,382202238450,94837128600,287365109850,10886125704700,3.51,KRX,MDCSTAT301

In [1]:
import pandas as pd
import pymysql
from sqlalchemy import create_engine, text
from datetime import datetime
import math

# =========================
# 0. DB 연결 설정
# =========================
DB_USER = ""
DB_PASSWORD ="" 
DB_HOST = ""
DB_PORT = 3306
DB_NAME = "qaima"

engine = create_engine(
    f"mysql+pymysql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}?charset=utf8mb4"
)

# =========================
# 1. CSV 읽기
# =========================
csv_path = r"short_selling.csv"

# stock_code 앞자리 0 보존하려면 dtype=str 권장
df = pd.read_csv(
    csv_path,
    encoding="utf-8",
    dtype={"stock_code": str}
)

print("raw rows =", len(df))
display(df.head())

raw rows = 700225

,stock_code,company_name,report_date,market_code,security_type,short_volume_total,short_volume_uptick_applied,short_volume_uptick_exempt,total_volume,short_volume_ratio,short_amount_total,short_amount_uptick_applied,short_amount_uptick_exempt,total_amount,short_amount_ratio,source,source_screen_id
0,095570,AJ네트웍스,2025-03-21,KOSPI,주권,177,0,177,74267,0.24,677910,0,677910,281297874,0.24,KRX,MDCSTAT301
1,006840,AK홀딩스,2025-03-21,KOSPI,주권,26,0,26,3674,0.71,269100,0,269100,37936350,0.71,KRX,MDCSTAT301
2,027410,BGF,2025-03-21,KOSPI,주권,171,0,171,40856,0.42,591660,0,591660,141199948,0.42,KRX,MDCSTAT301
3,282330,BGF리테일,2025-03-21,KOSPI,주권,59,0,59,98015,0.06,6655200,0,6655200,10991909800,0.06,KRX,MDCSTAT301
4,138930,BNK금융지주,2025-03-21,KOSPI,주권,27819,0,27819,1897341,1.47,302149590,0,302149590,20592791335,1.47,KRX,MDCSTAT301

In [2]:
print(df.columns.tolist())

['stock_code', 'company_name', 'report_date', 'market_code', 'security_type', 'short_volume_total', 'short_volume_uptick_applied', 'short_volume_uptick_exempt', 'total_volume', 'short_volume_ratio', 'short_amount_total', 'short_amount_uptick_applied', 'short_amount_uptick_exempt', 'total_amount', 'short_amount_ratio', 'source', 'source_screen_id']

In [3]:
# =========================
# 3. stock_code 정규화 + 날짜 파싱 / DB안정화
# =========================
def normalize_stock_code(x):
    if pd.isna(x):
        return None
    s = str(x).strip().replace('"', "").replace("'", "")
    if s == "":
        return None
    if s.isdigit():
        s = s.zfill(6)
    return s.upper()

df["stock_code"] = df["stock_code"].apply(normalize_stock_code)
df["report_date"] = pd.to_datetime(df["report_date"], errors="coerce").dt.date

df["source"] = df["source"].fillna("KRX").replace("", "KRX")
df["source_screen_id"] = df["source_screen_id"].fillna("MDCSTAT301").replace("", "MDCSTAT301")

print("rows =", len(df))
display(df.head())

rows = 700225

,stock_code,company_name,report_date,market_code,security_type,short_volume_total,short_volume_uptick_applied,short_volume_uptick_exempt,total_volume,short_volume_ratio,short_amount_total,short_amount_uptick_applied,short_amount_uptick_exempt,total_amount,short_amount_ratio,source,source_screen_id
0,095570,AJ네트웍스,2025-03-21,KOSPI,주권,177,0,177,74267,0.24,677910,0,677910,281297874,0.24,KRX,MDCSTAT301
1,006840,AK홀딩스,2025-03-21,KOSPI,주권,26,0,26,3674,0.71,269100,0,269100,37936350,0.71,KRX,MDCSTAT301
2,027410,BGF,2025-03-21,KOSPI,주권,171,0,171,40856,0.42,591660,0,591660,141199948,0.42,KRX,MDCSTAT301
3,282330,BGF리테일,2025-03-21,KOSPI,주권,59,0,59,98015,0.06,6655200,0,6655200,10991909800,0.06,KRX,MDCSTAT301
4,138930,BNK금융지주,2025-03-21,KOSPI,주권,27819,0,27819,1897341,1.47,302149590,0,302149590,20592791335,1.47,KRX,MDCSTAT301

In [4]:
#최신일 다시 확인
df_005930 = df[df["stock_code"] == "005930"].copy()
print("005930 rows =", len(df_005930))
print("005930 max report_date =", df_005930["report_date"].max())
display(df_005930.sort_values("report_date", ascending=False).head(20))

005930 rows = 243
005930 max report_date = 2026-03-20

,stock_code,company_name,report_date,market_code,security_type,short_volume_total,short_volume_uptick_applied,short_volume_uptick_exempt,total_volume,short_volume_ratio,short_amount_total,short_amount_uptick_applied,short_amount_uptick_exempt,total_amount,short_amount_ratio,source,source_screen_id
697802,005930,삼성전자,2026-03-20,KOSPI,주권,871381,341716,529665,42499576,2.05,174297078650,68424120950,105872957700,8466730499716,2.06,KRX,MDCSTAT301
694924,005930,삼성전자,2026-03-19,KOSPI,주권,1574488,809824,764664,29559268,5.33,316893032300,163109939200,153783093100,5955195854665,5.32,KRX,MDCSTAT301
692046,005930,삼성전자,2026-03-18,KOSPI,주권,888510,550958,337552,40259351,2.21,182794142200,112907987000,69886155200,8245401358813,2.22,KRX,MDCSTAT301
689167,005930,삼성전자,2026-03-17,KOSPI,주권,988960,639044,349916,29135546,3.39,193878982000,125150821750,68728160250,5711368340590,3.39,KRX,MDCSTAT301
686287,005930,삼성전자,2026-03-16,KOSPI,주권,777463,135634,641829,28269529,2.75,145622414450,25300601050,120321813400,5273027753250,2.76,KRX,MDCSTAT301
683406,005930,삼성전자,2026-03-13,KOSPI,주권,1547052,515520,1031532,26386624,5.86,283202360750,94358766550,188843594200,4835575044700,5.86,KRX,MDCSTAT301
680525,005930,삼성전자,2026-03-12,KOSPI,주권,853869,369684,484185,27460612,3.11,160084600200,69326395100,90758205100,5148439419250,3.11,KRX,MDCSTAT301
677644,005930,삼성전자,2026-03-11,KOSPI,주권,1003940,433319,570621,35631095,2.82,192629515200,83279507250,109350007950,6841140659906,2.82,KRX,MDCSTAT301
674763,005930,삼성전자,2026-03-10,KOSPI,주권,1659575,1150521,509054,50467350,3.29,311577899900,216381486500,95196413400,9489314157978,3.28,KRX,MDCSTAT301
671882,005930,삼성전자,2026-03-09,KOSPI,주권,2233430,552153,1681277,63586150,3.51,382202238450,94837128600,287365109850,10886125704700,3.51,KRX,MDCSTAT301
669002,005930,삼성전자,2026-03-06,KOSPI,주권,640227,477473,162754,42321957,1.51,119711891200,89284961150,30426930050,7877042133845,1.52,KRX,MDCSTAT301
666123,005930,삼성전자,2026-03-05,KOSPI,주권,1922650,1572150,350500,81292045,2.37,371399799900,303500056550,67899743350,15767405176166,2.36,KRX,MDCSTAT301
663244,005930,삼성전자,2026-03-04,KOSPI,주권,2564586,1994279,570307,138007637,1.86,468793205500,365654634550,103138570950,25074792242194,1.87,KRX,MDCSTAT301
660364,005930,삼성전자,2026-03-03,KOSPI,주권,1138390,1072592,65798,86333879,1.32,235742790600,222348189450,13394601150,17568799689650,1.34,KRX,MDCSTAT301
657484,005930,삼성전자,2026-02-27,KOSPI,주권,588952,568587,20365,68439905,0.86,128087874795,123692667295,4395207500,14807209714735,0.87,KRX,MDCSTAT301
654604,005930,삼성전자,2026-02-26,KOSPI,주권,1443985,1335850,108135,44281662,3.26,310141776500,287346159750,22795616750,9490901417838,3.27,KRX,MDCSTAT301
651724,005930,삼성전자,2026-02-25,KOSPI,주권,524788,366507,158281,36025232,1.46,106655543000,74527276250,32128266750,7313761303566,1.46,KRX,MDCSTAT301
648844,005930,삼성전자,2026-02-24,KOSPI,주권,205703,177786,27917,38821085,0.53,40668800050,35154749050,5514051000,7660700964858,0.53,KRX,MDCSTAT301
645963,005930,삼성전자,2026-02-23,KOSPI,주권,758644,512558,246086,35207920,2.15,147293823950,99320874150,47972949800,6822293771632,2.16,KRX,MDCSTAT301
643081,005930,삼성전자,2026-02-20,KOSPI,주권,234666,160027,74639,32355856,0.73,44511499650,30340859750,14170639900,6134580576330,0.73,KRX,MDCSTAT301

In [5]:
stock_df = pd.read_sql("""
SELECT stock_id, stock_code
FROM stock
""", engine)

stock_df["stock_code"] = stock_df["stock_code"].apply(normalize_stock_code)

print("stock rows =", len(stock_df))
display(stock_df.head())

stock rows = 922

   stock_id stock_code
0         1     000020
1         2     000040
2         3     000050
3         4     000070
4         5     000080

In [7]:
merged_005930 = merged[merged["stock_code"] == "005930"].copy()

print("005930 rows =", len(merged_005930))
print("005930 missing stock_id rows =", merged_005930["stock_id"].isna().sum())
print("005930 max report_date =", merged_005930["report_date"].max())

display(
    merged_005930.sort_values("report_date", ascending=False)[
        ["stock_code", "company_name", "report_date", "stock_id"]
    ].head(20)
)

005930 rows = 243
005930 missing stock_id rows = 0
005930 max report_date = 2026-03-20

       stock_code company_name report_date  stock_id
697802     005930         삼성전자  2026-03-20     276.0
694924     005930         삼성전자  2026-03-19     276.0
692046     005930         삼성전자  2026-03-18     276.0
689167     005930         삼성전자  2026-03-17     276.0
686287     005930         삼성전자  2026-03-16     276.0
683406     005930         삼성전자  2026-03-13     276.0
680525     005930         삼성전자  2026-03-12     276.0
677644     005930         삼성전자  2026-03-11     276.0
674763     005930         삼성전자  2026-03-10     276.0
671882     005930         삼성전자  2026-03-09     276.0
669002     005930         삼성전자  2026-03-06     276.0
666123     005930         삼성전자  2026-03-05     276.0
663244     005930         삼성전자  2026-03-04     276.0
660364     005930         삼성전자  2026-03-03     276.0
657484     005930         삼성전자  2026-02-27     276.0
654604     005930         삼성전자  2026-02-26     276.0
651724     005930         삼성전자  2026-02-25     276.0
648844     005930         삼성전자  2026-02-24     276.0
645963     005930         삼성전자  2026-02-23     276.0
643081     005930         삼성전자  2026-02-20     276.0

In [8]:
target_codes = ["005930", "000660"]

check_targets = merged[merged["stock_code"].isin(target_codes)].copy()

display(
    check_targets.groupby("stock_code").agg(
        rows=("stock_code", "count"),
        missing_stock_id=("stock_id", lambda s: s.isna().sum()),
        max_report_date=("report_date", "max")
    ).reset_index()
)

  stock_code  rows  missing_stock_id max_report_date
0     000660   243                 0      2026-03-20
1     005930   243                 0      2026-03-20

In [9]:
final_df = merged.dropna(subset=["stock_id", "report_date", "market_code", "security_type"]).copy()
final_df["stock_id"] = final_df["stock_id"].astype(int)

numeric_cols = [
    "short_volume_total",
    "short_volume_uptick_applied",
    "short_volume_uptick_exempt",
    "total_volume",
    "short_volume_ratio",
    "short_amount_total",
    "short_amount_uptick_applied",
    "short_amount_uptick_exempt",
    "total_amount",
    "short_amount_ratio",
]

for col in numeric_cols:
    final_df[col] = (
        final_df[col]
        .astype(str)
        .str.replace(",", "", regex=False)
        .replace({"nan": None, "None": None, "": None})
    )
    final_df[col] = pd.to_numeric(final_df[col], errors="coerce")

from datetime import datetime
now = datetime.now()
final_df["created_at"] = now
final_df["updated_at"] = now

final_cols = [
    "stock_id",
    "report_date",
    "market_code",
    "security_type",
    "short_volume_total",
    "short_volume_uptick_applied",
    "short_volume_uptick_exempt",
    "total_volume",
    "short_volume_ratio",
    "short_amount_total",
    "short_amount_uptick_applied",
    "short_amount_uptick_exempt",
    "total_amount",
    "short_amount_ratio",
    "source",
    "source_screen_id",
    "created_at",
    "updated_at",
]

final_df = final_df[final_cols].copy()

print("final rows =", len(final_df))
display(final_df.head())

final rows = 223580

,stock_id,report_date,market_code,security_type,short_volume_total,short_volume_uptick_applied,short_volume_uptick_exempt,total_volume,short_volume_ratio,short_amount_total,short_amount_uptick_applied,short_amount_uptick_exempt,total_amount,short_amount_ratio,source,source_screen_id,created_at,updated_at
0,1350,2025-03-21,KOSPI,주권,177,0,177,74267,0.24,677910,0,677910,281297874,0.24,KRX,MDCSTAT301,2026-03-28 21:21:49.434796,2026-03-28 21:21:49.434796
1,305,2025-03-21,KOSPI,주권,26,0,26,3674,0.71,269100,0,269100,37936350,0.71,KRX,MDCSTAT301,2026-03-28 21:21:49.434796,2026-03-28 21:21:49.434796
2,1185,2025-03-21,KOSPI,주권,171,0,171,40856,0.42,591660,0,591660,141199948,0.42,KRX,MDCSTAT301,2026-03-28 21:21:49.434796,2026-03-28 21:21:49.434796
3,1475,2025-03-21,KOSPI,주권,59,0,59,98015,0.06,6655200,0,6655200,10991909800,0.06,KRX,MDCSTAT301,2026-03-28 21:21:49.434796,2026-03-28 21:21:49.434796
4,1406,2025-03-21,KOSPI,주권,27819,0,27819,1897341,1.47,302149590,0,302149590,20592791335,1.47,KRX,MDCSTAT301,2026-03-28 21:21:49.434796,2026-03-28 21:21:49.434796

In [10]:
dup_cnt = final_df.duplicated(subset=["stock_id", "report_date"]).sum()
print("duplicated(stock_id, report_date) =", dup_cnt)

if dup_cnt > 0:
    final_df = final_df.drop_duplicates(subset=["stock_id", "report_date"], keep="last").copy()
    print("after drop_duplicates rows =", len(final_df))

duplicated(stock_id, report_date) = 0

In [12]:
insert_sql = """
INSERT INTO short_selling (
    stock_id,
    report_date,
    market_code,
    security_type,
    short_volume_total,
    short_volume_uptick_applied,
    short_volume_uptick_exempt,
    total_volume,
    short_volume_ratio,
    short_amount_total,
    short_amount_uptick_applied,
    short_amount_uptick_exempt,
    total_amount,
    short_amount_ratio,
    source,
    source_screen_id,
    created_at,
    updated_at
) VALUES (
    :stock_id,
    :report_date,
    :market_code,
    :security_type,
    :short_volume_total,
    :short_volume_uptick_applied,
    :short_volume_uptick_exempt,
    :total_volume,
    :short_volume_ratio,
    :short_amount_total,
    :short_amount_uptick_applied,
    :short_amount_uptick_exempt,
    :total_amount,
    :short_amount_ratio,
    :source,
    :source_screen_id,
    :created_at,
    :updated_at
)
"""

chunk_size = 5000
rows = final_df.to_dict(orient="records")

with engine.begin() as conn:
    for i in range(0, len(rows), chunk_size):
        chunk = rows[i:i+chunk_size]
        conn.execute(text(insert_sql), chunk)
        print(f"inserted {i + len(chunk)} / {len(rows)}")

inserted 5000 / 223580
inserted 10000 / 223580
inserted 15000 / 223580
inserted 20000 / 223580
inserted 25000 / 223580
inserted 30000 / 223580
inserted 35000 / 223580
inserted 40000 / 223580
inserted 45000 / 223580
inserted 50000 / 223580
inserted 55000 / 223580
inserted 60000 / 223580
inserted 65000 / 223580
inserted 70000 / 223580
inserted 75000 / 223580
inserted 80000 / 223580
inserted 85000 / 223580
inserted 90000 / 223580
inserted 95000 / 223580
inserted 100000 / 223580
inserted 105000 / 223580
inserted 110000 / 223580
inserted 115000 / 223580
inserted 120000 / 223580
inserted 125000 / 223580
inserted 130000 / 223580
inserted 135000 / 223580
inserted 140000 / 223580
inserted 145000 / 223580
inserted 150000 / 223580
inserted 155000 / 223580
inserted 160000 / 223580
inserted 165000 / 223580
inserted 170000 / 223580
inserted 175000 / 223580
inserted 180000 / 223580
inserted 185000 / 223580
inserted 190000 / 223580
inserted 195000 / 223580
inserted 200000 / 223580
inserted 205000 / 223580
inserted 210000 / 223580
inserted 215000 / 223580
inserted 220000 / 223580
inserted 223580 / 223580

In [13]:
check_005930 = pd.read_sql("""
SELECT ss.short_selling_id, s.stock_code, s.company_name, ss.report_date
FROM short_selling ss
JOIN stock s ON s.stock_id = ss.stock_id
WHERE s.stock_code = '005930'
ORDER BY ss.report_date DESC
LIMIT 20
""", engine)

display(check_005930)

    short_selling_id stock_code company_name report_date
0             223098     005930         삼성전자  2026-03-20
1             222177     005930         삼성전자  2026-03-19
2             221256     005930         삼성전자  2026-03-18
3             220335     005930         삼성전자  2026-03-17
4             219414     005930         삼성전자  2026-03-16
5             218493     005930         삼성전자  2026-03-13
6             217572     005930         삼성전자  2026-03-12
7             216651     005930         삼성전자  2026-03-11
8             215730     005930         삼성전자  2026-03-10
9             214809     005930         삼성전자  2026-03-09
10            213888     005930         삼성전자  2026-03-06
11            212967     005930         삼성전자  2026-03-05
12            212046     005930         삼성전자  2026-03-04
13            211125     005930         삼성전자  2026-03-03
14            210204     005930         삼성전자  2026-02-27
15            209283     005930         삼성전자  2026-02-26
16            208362     005930         삼성전자  2026-02-25
17            207441     005930         삼성전자  2026-02-24
18            206520     005930         삼성전자  2026-02-23
19            205599     005930         삼성전자  2026-02-20